### ISSUE TITLE
[BUILD FALIED] - When I run the game it gives me an error

### ISSUE THREAD

**Issue by rbarbosa95** [YoYoGames/GMEXT-GooglePlayPassLicensing#1]
Hello everyone, I am getting an error that whenever I have to run the game with an expression pointing to the SDK I get the following error would anyone have any idea what it could be? 

![Screenshot 2024-05-06 131413](https://github.com/YoYoGames/GMEXT-GooglePlayPassLicensing/assets/15218743/7af5676c-a0f1-4e7b-bf5e-d3aaa6be014b)

`"FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':gradle:generateReleaseUnitTestStubRFile'.
> Manifest file does not exist: C:\Users\Ramon\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\GooglePlay_71A54692_1922B94B\android\Default\gradle\AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2023.1.1.81/android/runner\gradle\gradlew.bat exited with non-zero status (1)
elapsed time 00:00:22.6642549s for command "C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2023.1.1.81/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\Ramon\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Android Run started at 05/06/2024 13:13:19
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window."
`

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.
